
services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-db
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_PASSWORD: '1234'
    volumes:
      - oracle-db-data:/opt/oracle/oradata
    ports:
      - "1521:1521"
volumes:
  oracle-db-data:
